// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ItemComponent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full p-3 flex flex-row text-center rounded-md bg-black text-white gap-10 border-gray border-4\" x-data=\"{ item: item }\" x-init=\"$watch(&#39;item&#39;, async (value) =&gt; {const newItem = await update(value); newItem != null ? (error = false, items = items.map(ai =&gt; ai.id === item.id ? newItem : ai)): error = true})\"><div class=\"w-full h-full flex flex-row items-center justify-center lg:gap-10 gap-5\"><div class=\"w-1/2 max-w-1/2 flex justify-center items-center truncate\"><h1 class=\"text-white\" x-text=\"item.name\"></h1></div><div class=\"flex flex-row lg:gap-5 gap-2 justify-center items-center lg:w-1/4\"><button class=\"bg-gray p-3 rounded-md text-white\" @click=\"item.quantity === 1 ? (confirm = true, deleteItem = item) : item.quantity--\">-1</button><p class=\"w-10 flex justify-center items-center text-center p-2 rounded-md border-2 border-gray\" x-text=\"item.quantity\"></p><button class=\"bg-gray p-3 rounded-md text-white\" @click=\"item.quantity += 1\">+1</button></div><div class=\"flex items-center justify-center\"><button class=\"bg-gray p-3 rounded-md text-white flex flex-row\" @click=\"item.location = item.location == 1 ? 0 : 1\">Move</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
